
[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = false

[colors.bright]
black = "0x686868"
blue = "0x57c7ff"
cyan = "0x9aedfe"
green = "0x5af78e"
magenta = "0xff6ac1"
red = "0xff5c57"
white = "0xf1f1f0"
yellow = "0xf3f99d"

[colors.normal]
black = "0x282a36"
blue = "0x7aD5F1"
cyan = "0x9aedfe"
green = "0xa5e179"
magenta = "0xff6ac1"
red = "0xff5c57"
white = "0xf1f1f0"
yellow = "0xf3f99d"

[colors.primary]
background = "0x2A2F38"
foreground = "0xe1e3e4"

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "Never"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"

[font.italic]
style = "Oblique"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 1

[[keyboard.bindings]]
chars = "θ"
key = "H"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "α"
key = "R"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mode = "~Search"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "Copy"
key = "Y"
mode = "Vi|~Search"

[scrolling]
history = 10000

[terminal.shell]
args = ["--login"]
program = "/bin/zsh"

[window]
decorations = "none"
dynamic_title = true
opacity = 1.0
startup_mode = "Maximized"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 155
lines = 36

[window.padding]
x = 0
y = 0

[window.position]
x = 104
y = 132

[general]
live_config_reload = true

[terminal]
