format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$direnv\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$status\
$line_break\
$jobs\
$battery\
$time\
$os\
$container\
$shell\
$character"""

[character]
success_symbol = "[➜](bold green)"
error_symbol  = "[➜](bold red)"

[python]
python_binary = ["./venv/bin/python", "python3", "python", "python2"]

[hostname]
disabled = false
ssh_only = true
format = "[@$hostname](green) "

[directory]
truncate_to_repo = true

[status]
disabled = false
style = "red"
symbol = ''
format = 'returned [$symbol$common_meaning$maybe_int]($style) '
map_symbol = true

[aws]
disabled = true
